spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-clean.sql
# Prevent Spring from loading data.sql in clean profile
spring.sql.init.data-locations=
spring.jpa.hibernate.ddl-auto=none
# Checks for and loads new schema if necessary, DOES NOT LOAD TEST DATA from data.sql here
# IT WILL LEAVE an existing database schema and data if it already exists
