spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-dev.sql
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.hibernate.ddl-auto=none

# DROPS and loads new schema then loads new seed test data.
# IT WILL DELETE the existing database schema and data if it already exists!!

