spring.application.name=sota_tracking
spring.datasource.url=jdbc:postgresql://localhost:5432/sota_data
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:admin}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=env



